const $ = (id)=>{
  return document.querySelector(`#${id}`);
};
const movieDetailBackBtn = $("movie-detail-header-back-btn");
const headerContainer = $("header-container");
const movieDetailPage = $("movie-detail-section");
const movieDetailImage = $("movie-detail-header-img");
const movieDetailTitle = $("movie-detail-header-title");
const movieDetailYear = $("movie-detail-header-year");
const movieDetailDuration = $("movie-detail-duration");
const movieDetailCategoriesContainer = $("movie-detail-categories-container");
const movieDetailOverview = $("movie-detail-overview");
const movieDetailRate = $("movie-detail-rate");
const movieDetailDirector = $("movie-detail-director");
const movieDetailCastContainer = $("movie-detail-cast-container");
const movieDetailSimilarContainer = $("movie-detail-similar-container");
const trendSection = $("recommended-section");
const trendImageNode = $("recommended-img");
const trendTitleNode = $("recommended-movie-title");
const trendCategoriesContainer = $("recommended-categories-container");
const trendOverviewNode = $("recommended-movie-description");
const trendRateNode = $("recommended-movie-rate");
const trendLanguageNode = $("recommended-movie-language");
const sectionsContainer = $("sections-container");
const movieNav = $("navbar-movie");
const tvNav = $("navbar-tv");